import { useEffect, useState } from "react";
import api from "../services/api";

export default function PatientDashboard() {
  const [doctors, setDoctors] = useState([]);
  const [prescriptions, setPrescriptions] = useState([]);
  const [specialization, setSpecialization] = useState("");
  const [booking, setBooking] = useState({ doctorId: "", date: "", startTime: "", endTime: "" });
  const [bookingMessage, setBookingMessage] = useState("");
  const [searchMessage, setSearchMessage] = useState("");
  const [error, setError] = useState("");
  const [successPrescription, setSuccessPrescription] = useState("");

  // Fetch doctors
  const fetchDoctors = async (specialization) => {
    try {
      setError(""); setSearchMessage("");
      const res = await api.get(`/api/patient/doctors?specialization=${specialization}`);
      setDoctors(res.data);
      if (res.data.length === 0) setSearchMessage("No doctors found");
    } catch (err) {
      console.error(err);
      setError("Failed to fetch doctors");
    }
  };

  // Fetch only undownloaded prescriptions
  const fetchPrescriptions = async () => {
    try {
      const res = await api.get("/api/patient/prescriptions");
      const undownloaded = res.data.filter(p => !p.downloaded);
      setPrescriptions(undownloaded);
    } catch (err) {
      console.error(err);
      setError("Failed to load prescriptions");
    }
  };

  // Book appointment
  const bookAppointment = async () => {
    setError(""); setBookingMessage("");
    const { doctorId, date, startTime, endTime } = booking;
    if (!doctorId || !date || !startTime || !endTime) { setError("Fill all fields"); return; }
    if (endTime <= startTime) { setError("End time must be after start time"); return; }

    try {
      const res = await api.post("/api/patient/appointments", booking);
      setBookingMessage(`✅ ${res.data.message}`);
      setBooking({ doctorId: "", date: "", startTime: "", endTime: "" });
      fetchPrescriptions();
    } catch (err) {
      console.error(err);
      setError("Booking failed");
    }
  };

  const downloadPrescription = async (p) => {
  try {
    if (!p.pdfUrl) {
      setError("Prescription file not available yet");
      return;
    }

    window.open(p.pdfUrl, "_blank");

    await api.put(`/api/doctor/prescriptions/${p._id}/download`);

    setPrescriptions(prev => prev.filter(x => x._id !== p._id));

    setSuccessPrescription(
      `✅ Appointment completed & prescription generated by Dr. ${p.doctorId.userId.name}`
    );
  } catch (err) {
    console.error(err);
    setError("Failed to download prescription");
  }
};
useEffect(() => {
  console.log("PRESCRIPTIONS FROM API 👉", prescriptions);
}, [prescriptions]);


  //useEffect(() => { fetchPrescriptions(); }, []);

  return (
    <div style={{ padding: 20 }}>
      <h2>👤 Patient Dashboard</h2>
      {error && <p style={{ color: "red" }}>{error}</p>}
      {searchMessage && <p style={{ color: "blue" }}>{searchMessage}</p>}
      {bookingMessage && <p style={{ color: "green" }}>{bookingMessage}</p>}
      {successPrescription && <p style={{ color: "green" }}>{successPrescription}</p>}

      {/* Doctor Search */}
      <h3>🔍 Search Doctors</h3>
      <input placeholder="Specialization" value={specialization} onChange={(e) => setSpecialization(e.target.value)} />
      <button onClick={() => fetchDoctors(specialization)}>Search</button>
      <ul>
        {doctors.map(doc => (
          <li key={doc._id}>
            Dr. {doc.userId.name} ({doc.specialization})
            <button style={{ marginLeft: 10 }} onClick={() => setBooking({ ...booking, doctorId: doc._id })}>Select</button>
          </li>
        ))}
      </ul>

      {/* Book Appointment */}
      <h3>📅 Book Appointment</h3>
      <input type="date" value={booking.date} onChange={(e) => setBooking({ ...booking, date: e.target.value })} />
      <input type="time" value={booking.startTime} onChange={(e) => setBooking({ ...booking, startTime: e.target.value })} />
      <input type="time" value={booking.endTime} onChange={(e) => setBooking({ ...booking, endTime: e.target.value })} />
      <button disabled={!booking.doctorId} onClick={bookAppointment}>Book Appointment</button>

      {/* Prescriptions */}
      <h3>💊 Prescriptions</h3>
      <ul>
        {prescriptions.map(p => (
          <li key={p._id}>
            Dr. {p.doctorId.userId.name}
            <button style={{ marginLeft: 10 }} onClick={() => downloadPrescription(p)}>Download</button>
          </li>
        ))}
      </ul>
    </div>
  );
}
